config/routes.rb
Rails.application.routes.draw do
  resources :testa

  resources :users

end

app/models/testum.rb
class Testum < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/testa_controller.rb
class TestaController < ApplicationController
  before_action :set_testum, only: [:show, :edit, :update, :destroy]

  # GET /testa
  # GET /testa.json
  def index
    @testa = Testum.all
  end

  # GET /testa/1
  # GET /testa/1.json
  def show
  end

  # GET /testa/new
  def new
    @testum = Testum.new
  end

  # GET /testa/1/edit
  def edit
  end

  # POST /testa
  # POST /testa.json
  def create
    @testum = Testum.new(testum_params)

    respond_to do |format|
      if @testum.save
        format.html { redirect_to @testum, notice: 'Testum was successfully created.' }
        format.json { render :show, status: :created, location: @testum }
      else
        format.html { render :new }
        format.json { render json: @testum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testa/1
  # PATCH/PUT /testa/1.json
  def update
    respond_to do |format|
      if @testum.update(testum_params)
        format.html { redirect_to @testum, notice: 'Testum was successfully updated.' }
        format.json { render :show, status: :ok, location: @testum }
      else
        format.html { render :edit }
        format.json { render json: @testum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testa/1
  # DELETE /testa/1.json
  def destroy
    @testum.destroy
    respond_to do |format|
      format.html { redirect_to testa_url, notice: 'Testum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testum
      @testum = Testum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testum_params
      params.require(:testum).permit(:t)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/testa_helper.rb
module TestaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/testa/_form.html.erb
<%= form_for(@testum) do |f| %>
  <% if @testum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testum.errors.count, "error") %> prohibited this testum from being saved:</h2>

      <ul>
      <% @testum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :t %><br>
    <%= f.text_field :t %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testa/edit.html.erb
<h1>Editing Testum</h1>

<%= render 'form' %>

<%= link_to 'Show', @testum %> |
<%= link_to 'Back', testa_path %>

app/views/testa/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testa</h1>

<table>
  <thead>
    <tr>
      <th>T</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testa.each do |testum| %>
      <tr>
        <td><%= testum.t %></td>
        <td><%= link_to 'Show', testum %></td>
        <td><%= link_to 'Edit', edit_testum_path(testum) %></td>
        <td><%= link_to 'Destroy', testum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testum', new_testum_path %>

app/views/testa/new.html.erb
<h1>New Testum</h1>

<%= render 'form' %>

<%= link_to 'Back', testa_path %>

app/views/testa/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>T:</strong>
  <%= @testum.t %>
</p>

<%= link_to 'Edit', edit_testum_path(@testum) %> |
<%= link_to 'Back', testa_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>